const char *designdoc_orderbook="{\"_id\": \"_design/orderbook\", \"couchapp\": {\"signatures\": {}, \"objects\":"
" {}, \"manifest\": [\"views/\", \"views/all/\", \"views/all/reduce.js\", \"views"
"/all/map.js\", \"views/levels-0/\", \"views/levels-0/reduce.js\", \"views/levels"
"-0/map.js\", \"views/levels-5/\", \"views/levels-5/reduce.js\", \"views/levels-5"
"/map.js\", \"language\"]}, \"_attachments\": {}, \"language\": \"javascript\", \""
"views\": {\"all\": {\"map\": \"function(doc) {\\n\\tif (doc._id.substr(0,2) == \\"
"\"o.\\\"\\n\\t\\t&& !doc.finished\\n\\t\\t&& doc.status == \\\"active\\\"\\n\\t\\"
"t&& (doc.type == \\\"limit\\\" || doc.type == \\\"postlimit\\\")) {\\n\\t\\t\\te"
"mit([doc.dir==\\\"buy\\\"?0:1,doc.limitPrice], doc.size);\\n\\t\\t}\\t\\n}\", \""
"reduce\": \"function(keys, values, rereduce) {\\n\\t\\n\\tvar size = 0;\\n\\tvar"
" count = 0;\\n\\tif (rereduce) {\\n\\t\\t\\n\\t\\tvalues.forEach(function(x) {\\"
"n\\t\\t\\tsize = size + x.size;\\n\\t\\t\\tcount = count + x.count;\\n\\t\\t});\\"
"n\\t\\t\\n\\t} else {\\n\\t\\t\\n\\t\\tvalues.forEach(function(x) {\\n\\t\\t\\ts"
"ize = size + x;\\n\\t\\t\\tcount++;\\n\\t\\t});\\n\\t\\t\\n\\t}\\n\\treturn {\\n"
"\\t\\t\\\"size\\\":size,\\n\\t\\t\\\"count\\\":count\\n\\t}\\n}\"}, \"levels-5\""
": {\"map\": \"function(doc) {\\n\\tif (doc._id.substr(0,2) == \\\"o.\\\"\\n\\t\\"
"t&& !doc.finished\\n\\t\\t&& doc.status == \\\"active\\\"\\n\\t\\t&& (doc.type ="
"= \\\"limit\\\" || doc.type == \\\"postlimit\\\")) {\\n\\t\\t\\n\\t\\t\\tvar pri"
"ce = doc.limitPrice;\\n\\t\\t\\tvar a = [doc.dir==\\\"buy\\\"?0:1,Math.floor(pri"
"ce)]\\n\\t\\t\\tfor (var i = 10; i <= 100000; i = i * 10) {\\n\\t\\t\\t\\tvar p "
"= Math.floor(price * i) % 10;\\n\\t\\t\\t\\ta.push(p);\\n\\t\\t\\t}\\n\\t\\t\\n\\"
"t\\t\\temit(a, doc.size);\\n\\t\\t}\\t\\n}\", \"reduce\": \"function(keys, value"
"s, rereduce) {\\n\\t\\n\\tvar size = 0;\\n\\tvar count = 0;\\n\\tif (rereduce) {"
"\\n\\t\\t\\n\\t\\tvalues.forEach(function(x) {\\n\\t\\t\\tsize = size + x.size;\\"
"n\\t\\t\\tcount = count + x.count;\\n\\t\\t});\\n\\t\\t\\n\\t} else {\\n\\t\\t\\"
"n\\t\\tvalues.forEach(function(x) {\\n\\t\\t\\tsize = size + x;\\n\\t\\t\\tcount"
"++;\\n\\t\\t});\\n\\t\\t\\n\\t}\\n\\treturn {\\n\\t\\t\\\"size\\\":size,\\n\\t\\"
"t\\\"count\\\":count\\n\\t}\\n}\"}, \"levels-0\": {\"map\": \"function(doc) {\\n"
"\\tif (doc._id.substr(0,2) == \\\"o.\\\"\\n\\t\\t&& !doc.finished\\n\\t\\t&& doc"
".status == \\\"active\\\"\\n\\t\\t&& (doc.type == \\\"limit\\\" || doc.type == \\"
"\"postlimit\\\")) {\\n\\t\\t\\n\\t\\t\\tvar price = doc.limitPrice;\\n\\t\\t\\tv"
"ar a = [doc.dir==\\\"buy\\\"?0:1,Math.floor(price/100000)]\\n\\t\\t\\tfor (var i"
" = 10000; i >= 1; i = i / 10) {\\n\\t\\t\\t\\tvar p = Math.floor(price / i) % 10"
";\\n\\t\\t\\t\\ta.push(p);\\n\\t\\t\\t}\\n\\t\\t\\n\\t\\t\\temit(a, doc.size);\\"
"n\\t\\t}\\t\\n}\", \"reduce\": \"function(keys, values, rereduce) {\\n\\t\\n\\tv"
"ar size = 0;\\n\\tvar count = 0;\\n\\tif (rereduce) {\\n\\t\\t\\n\\t\\tvalues.fo"
"rEach(function(x) {\\n\\t\\t\\tsize = size + x.size;\\n\\t\\t\\tcount = count + "
"x.count;\\n\\t\\t});\\n\\t\\t\\n\\t} else {\\n\\t\\t\\n\\t\\tvalues.forEach(func"
"tion(x) {\\n\\t\\t\\tsize = size + x;\\n\\t\\t\\tcount++;\\n\\t\\t});\\n\\t\\t\\"
"n\\t}\\n\\treturn {\\n\\t\\t\\\"size\\\":size,\\n\\t\\t\\\"count\\\":count\\n\\t"
"}\\n}\"}}}\n";
unsigned int designdoc_orderbook_length=2749;
